### PR TITLE
Command Tree for Phoenix Software International (E)JES RESTapi.

### PR DESCRIPTION
**Pull request by Tulsagrammer**
Command Tree for Phoenix Software International (E)JES RESTapi.

### CODE REVIEW

**Comment by DonnaHudi** [comment]
Please note that this is incorrectly titled as Command Tree for Phoenix Software International (E)JES RESTapi.
It instead should be titled Command Tree for Phoenix Software International (E)JES plug-in for Zowe CLI

**Review by traeok — APPROVED** [review]

**Comment by Joe-Winchester** [comment]
Hi @awharn ,  super thank you for merging this PR.  
It looks like it hasn't yet made it to https://docs.zowe.org/stable/web_help/.  Do you know if there is an additional step that needs to occur to trigger the CLI syntax to go live ?
Cheers.

**Comment by awharn** [comment]
Hi @Joe-Winchester. The web help on the docs-site usually gets updated when a Zowe release is taking place, since Zowe CLI commands, options, and descriptions are often changing, and the goal is to reflect the commands and options available at the time of the Zowe release. There is no automation in this repository to create a PR against the docs-site and upload our artifacts. The next planned update is around the Zowe 2.15 release toward the end of this month. If you prefer, I can open a PR against the docs-site with the updates here to see if they can get it in off-cycle.

**Comment by awharn** [comment]
@DonnaHudi @Joe-Winchester Ok, I aim to have the PR opened against the docs-site before the end of the day.

**Comment by DonnaHudi** [comment]
Thank you @awharn

**Pull request merged**
